apiVersion: operator.dtstack.com/v1
kind: Mole
metadata:
  name: example-mole
spec:
  # Add fields here
  product:
    product_name: wxtest
    product_version: v1.0.0
    parent_product_name: dtest
    service:
      "nginx":
        is_deploy_ingress: true
        instance:
          image: nginx:latest
          config_path : /config
          service:
            annotations:
              "name": test
          deployment:
            ports:
              - 80
              - 81
