apiVersion: operator.dtstack.com/v1
kind: Mole
metadata:
  name: example-mole
  namespace: dtstack-system
spec:
  # Add fields here
  product:
    product_name: wxtest
    product_version: v1.0.0
    parent_product_name: dtest
    deploy_uuid: wx-test-test
    clusterId: 1
    pid: 1
    service:
      "nginx":
        is_deploy_ingress: true
        version: 1.9.1
        instance:
          config_path : /config
          deployment:
            image: nginx:latest
            replicas: 1
            ports:
              - 80
