apiVersion: operator.dtstack.com/v1
kind: Mole
metadata:
  name: example-mole
spec:
  # Add fields here
  product:
    product_name: "wx_test"
    service:
      instance:
        version: "0.0.1"
        service_display: "test"
        depends_on:
          - "dtest"
